---
- name: Gather facts from Junos devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Save Junos output to destination files
      juniper_junos_command:
        command: 
         - "show version"
         - "show chassis hardware"
        dest: "/tmp/{{ inventory_hostname }}.output"    
      register: response

    - name: Print the command output
      debug:
        var: response
        
    # Sending an e-mail using Gmail SMTP servers
    - mail:
       host: mail.smtp2go.com
       port: 443
       secure: always
       username: roger.wiklund@gmail.com
       password: KIA0xiK2eo7r
       to: Roger Wiklund <rwiklund@juniper.net>
       subject: Ansible-report
       body: 'System test has been successfully provisioned.'
      delegate_to: localhost
