---
- name: Housekeeping
  hosts: all
  connection: local
  gather_facts: no
  run_once: true
  tags: always
  tasks:
   - name: remove host config temp directory
     file: path=/root/ansible_tmp/config state=absent
   - name: remove host output temp directory  
     file: path=/root/ansible_tmp/output state=absent
   - name: create host config temp directory
     file: path=/root/ansible_tmp/config state=directory
   - name: create host output temp directory
     file: path=/root/ansible_tmp/output state=directory
  
- name: Gather facts from Junos devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Save Junos output to destination files
      juniper_junos_command:
        command: 
    #    - "show configuration"
    #    - "show chassis hardware"
        dest: "/root/ansible_tmp/output/{{ inventory_hostname }}.output"  
        
    # Concatenate all output files to a single text file    
    - assemble:
       src: /root/ansible_tmp/output/
       regexp: '(.*\.output$)'
       dest: /root/ansible_tmp/output/gather_facts.txt
       delimiter: '-----------------'
      run_once: true 
      
    # Send an email with gather_facts.txt attatchment
    - mail:
       host: mail.smtp2go.com
       port: 443
       secure: always
       from: Ansible AWX <ansible-awx@juniper.net>
       to: '{{ to_email }}'
       subject: Ansible AWX Gather Facts Report
       body: 'Gather Fatcs playbook has been successfully executed.'
       attach: /root/ansible_tmp/output/gather_facts.txt
      delegate_to: localhost
      run_once: true
