---
- name: Gather facts from Junos devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: save output to dest
      juniper_junos_command:
        command: "show version"
        dest: "/tmp/{{ inventory_hostname }}.output"
