---
- name: Gather facts from Junos devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Save Junos output to destination files
      juniper_junos_command:
        command: 
         - "show version"
         - "show chassis hardware"
        dest: "/tmp/{{ inventory_hostname }}.output"
