---
- name: Housekeeping
  hosts: all
  connection: local
  gather_facts: no
  run_once: true
  tags: always
  tasks:
   - name: remove host config temp directory
     file: path=/root/ansible_tmp/config state=absent
   - name: remove host output temp directory  
     file: path=/root/ansible_tmp/output state=absent
   - name: create host config temp directory
     file: path=/root/ansible_tmp/config state=directory
   - name: create host output temp directory
     file: path=/root/ansible_tmp/output state=directory
     
- name: Playbook for Junos Common 
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    - common
  vars_files:
   - /root/crypto.yml
  tags: common
  
- name: Playbook for Junos Switches 
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    - switches
  vars_files:
   - /root/crypto.yml  
  tags: switches
  
  - name: Playbook for Junos Switches 
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    - vlan
  tags: vlan
