---
- name: Playbook for Junos Common 
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    - common
  vars_files:
   - /root/crypto.yml
  tags: common
  
- name: Playbook for Junos Switches 
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
    - switches
  vars_files:
   - /root/crypto.yml  
  tags: switches
