---
- name: Send Slack Notifications
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  
  # Insert hostname.diff in the top of each .diff
  - lineinfile:
     path: "/root/ansible_tmp/output/{{ inventory_hostname }}.diff"
     insertbefore: '\['
     firstmatch: yes
     line: '{{ inventory_hostname }}.diff'
  
  # Concatenate all output diffs to a single text file    
  - assemble:
     src: /root/ansible_tmp/output/
     regexp: '(.*\.diff$)'
     dest: /root/ansible_tmp/output/junos_config_diff.txt
     delimiter: \n
    run_once: true 

  - name: Run script to send diff to Github Gists
    local_action: 'shell sh /root/update.sh'
    run_once: true
  
  - name: Send notification message via Slack
    slack:
      token: '{{ slack_token }}'
      msg: 'User {{ tower_user_name }} made configuration changes - https://gist.github.com/rogerwiklund/f63549614dcd14b8fa332202ccc95515'
    delegate_to: localhost
    run_once: true

