---
- name: Generate common Junos config
  template: src=main.conf.j2 dest=/root/ansible_tmp/{{ inventory_hostname }}.conf
  tags: build

- name: Configure Junos devices with common config
  juniper_junos_config:
    timeout: 60
    diff: true
    load: 'set'
    src: "/root/ansible_tmp/{{ inventory_hostname }}.conf"
  register: response
  tags: deploy
  
- name: Print the complete response.
  debug:
    var: response
