---
- name: Generate common Junos config
  template: src=main.conf.j2 dest=/root/ansible_tmp/config/{{ inventory_hostname }}.conf
  tags: build

- name: Configure Junos devices with common config
  juniper_junos_config:
    timeout: '60'
    retrieve: 'candidate'
    load: 'set'
    src: "/root/ansible_tmp/config/{{ inventory_hostname }}.conf"
    dest_dir: "/root/ansible_tmp/output/"
    return_output: 'false'
  register: response
  tags: deploy

  # Insert hostname.diff in the top of each .diff
- lineinfile:
   path: "/root/ansible_tmp/output/{{ inventory_hostname }}.diff"
   insertbefore: '\['
   firstmatch: yes
   line: '{{ inventory_hostname }}.diff'
  
  # Concatenate all output diffs to a single text file    
- assemble:
   src: /root/ansible_tmp/output/
   regexp: '(.*\.diff$)'
   dest: /root/ansible_tmp/output/junos_config_diff.txt
   delimiter: \n
  run_once: true 
  
- name: Send notification message via Slack
  slack:
   token: '{{ slack_token }}'
   channel: '#ansible'
   msg: 'User {{ tower_user_id }} made configuration changes - https://gist.github.com/rogerwiklund/f63549614dcd14b8fa332202ccc95515'
  delegate_to: localhost
  run_once: true
