---
- name: Generate common Junos config
  template: src=main.conf.j2 dest=/root/ansible_tmp/config/{{ inventory_hostname }}.conf
  tags: build

- name: Configure Junos devices with common config
  juniper_junos_config:
    timeout: 60
    load: 'set'
    src: "/root/ansible_tmp/config/{{ inventory_hostname }}.conf"
  register: response
  tags: deploy
  
- name: Print config diff
  debug:
   var: response
    
- name: Write diff to files                                                                                
  copy:                                                                                              
   content: "{{ response.diff | to_yaml }}"
   dest: "/root/ansible_tmp/output/{{ inventory_hostname }}.diff"
